//SCRIPT CRIADO PARA REDUZIR O TAMANHO DAS OPTIONS DENTRO DO SELECT DE UF

export const ufList = [
    {value: "RO", label: "Rondônia"},
    {value: "AC", label: "Acre"},
    {value: "AM", label: "Amazonas"},
    {value: "RR", label: "Roraima"},
    {value: "PA", label: "Pará"},
    {value: "AP", label: "Amapá"},
    {value: "TO", label: "Tocantins"},
    {value: "MA", label: "Maranhão"},
    {value: "PI", label: "Piauí"},
    {value: "CE", label: "Ceará"},
    {value: "RN", label: "Rio G. do Norte"},
    {value: "PB", label: "Paraíba"},
    {value: "PE", label: "Pernambuco"},
    {value: "AL", label: "Alagoas"},
    {value: "SE", label: "Sergipe"},
    {value: "BA", label: "Bahia"},
    {value: "MG", label: "Minas Gerais"},
    {value: "ES", label: "Espirito Santo"},
    {value: "RJ", label: "Rio de Janeiro"},
    {value: "SP", label: "São Paulo"},
    {value: "PR", label: "Paraná"},
    {value: "SC", label: "Santa Catarina"},
    {value: "RS", label: "Rio G. do Sul"},
    {value: "MS", label: "Mato G. do Sul"},
    {value: "MT", label: "Mato Grosso"},
    {value: "GO", label: "Goiás"},
    {value: "DF", label: "Distrito Federal"},
]